name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website (shallow + submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Update submodule to latest (shallow)
        run: |
          git -c protocol.version=2 submodule update --init --recursive --depth 1
          git -c protocol.version=2 submodule update --remote --recursive --depth 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        if: github.event.inputs.environment == 'production'
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_URL: https://staituned.com

      - name: Build for development
        if: github.event.inputs.environment == 'development'
        run: npm run build:dev
        env:
          NODE_ENV: development
          NEXT_PUBLIC_BASE_URL: https://dev.staituned.com

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Production
        if: github.event.inputs.environment == 'production'
        run: firebase deploy --project staituned-prod --only hosting:production --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Development
        if: github.event.inputs.environment == 'development'
        run: firebase deploy --project staituned-prod --only hosting:development --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
