name: Webhook Content Update

on:
  # Repository dispatch trigger (for webhooks from other repos)
  repository_dispatch:
    types: [webhook-update, content-sync]
  
  # Manual trigger
  workflow_dispatch:
  
  # HTTP webhook via repository dispatch API
  # Can be triggered via: POST /repos/stAItuned/website/dispatches

# Ensure the workflow has necessary permissions
permissions:
  contents: write        # To push commits
  actions: read         # To read workflow info

jobs:
  update-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          # Use custom token if available, fallback to GITHUB_TOKEN
          token: ${{ secrets.WEBSITE_DISPATCH_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Ensure full history for submodule operations
      
      - name: Update CMS submodule
        run: |
          git config --global user.name 'Content Updater'
          git config --global user.email 'noreply@staituned.com'
          
          # Pull latest from CMS
          git submodule update --remote cms
          
          # Check for changes
          if ! git diff --quiet HEAD -- cms; then
            git add cms
            git commit -m "📝 Update content from CMS webhook"
            git push
            echo "✅ Content updated successfully"
          else
            echo "ℹ️ No content changes detected"
          fi
      
      - name: Trigger build
        run: |
          # This will trigger your deployment platform (Vercel, Netlify, etc.)
          echo "🔄 Build triggered by content update"
